name: Run statis analysis (2)

on:
  push:
  pull_request:

jobs:
  golangci:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - uses: actions/checkout@master

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: |
          cd myapp
          golangci-lint run
