name: Run statis analysis (1)

on:
  push:
  pull_request:

jobs:
  golangci:
    runs-on: ubuntu:22.04

    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - uses: actions/checkout@master

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: myapp
